name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Configure MYSQL server
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
      - name: Install packages
        run: npm install
      - name: Run tests
        run: npm run test
